createDialog "MenuJoueur";
ctrlSetText[77771,format["Argent en banque : %1",(player getVariable "MonArgent")]];
ctrlSetText[77772,format["Argent Placé sur Livré : %1",revenue]];
ctrlSetText[77775,format["Poid inventaire : %1",(player getVariable "Poids")]];

if (LicenseV == 0) then  {PermisVoiture= "Non Posséde"} else {PermisVoiture = "Posséde"};
if (LicenseC == 0) then  {PermisPoidLourd= "Non Posséde"} else {PermisPoidLourd = "Posséde"};
if (LicenseB == 0) then  {PermisBateau= "Non Posséde"} else {PermisBateau = "Posséde"};
if (LicenseA == 0) then  {PermisPilote= "Non Posséde"} else {PermisPilote = "Posséde"};
if (LicenseAr == 0) then  {permisArme= "Non Posséde"} else {permisArme = "Posséde"};

lbAdd [77773,format["Permis Voiture : %1",(PermisVoiture)]];
lbAdd [77773,format["Permis Poid lourds : %1",(PermisPoidLourd)]];
lbAdd [77773,format["Permis bateau : %1",(PermisBateau)]];
lbAdd [77773,format["License Pilote : %1",(PermisPilote)]];
lbAdd [77773,format["Permis Arme : %1",(permisArme)]];
if (playerside == civilian) then
	{
Ressources = "0";
Ressources1 = "0";
Ressources2 = "0";
Ressources3 = "0";
Ressources4 = "0";
Ressources5 = "0";
Ressources6 = "0";
Ressources7 = "0";
Ressources8 = "0";
Ressources9 = "0";
Ressources10 = "0";
Ressources11 = "0";
Ressources12 = "0";
Ressources13 = "0";
Ressources14 = "0";
Ressources15 = "0";
Ressources16 = "0";
if (!isnil {player getVariable "Heroine"}) then {Ressources = (player getVariable "Héroine")};
if (!isnil {player getVariable "Pomme"}) then {Ressources1 = (player getVariable "Pomme")};
if (!isnil {player getVariable "Sable"}) then {Ressources11 = (player getVariable "Sable")};
if (!isnil {player getVariable "Bois"}) then {Ressources12 = (player getVariable "Bois")};
if (!isnil {player getVariable "Pierre"}) then {Ressources13 = (player getVariable "Pierre")};
if (!isnil {player getVariable "Poisson"}) then {Ressources2 = (player getVariable "Poisson")};
if (!isnil {player getVariable "Petrole"}) then {Ressources3 = (player getVariable "Petrole")};
if (!isnil {player getVariable "Fer"}) then {Ressources4 = (player getVariable "Fer")};
if (!isnil {player getVariable "FerTransformer"}) then {Ressources10 = (player getVariable "Fer")};
if (!isnil {player getVariable "Charbon"}) then {Ressources5 = (player getVariable "Charbon")};
if (!isnil {player getVariable "Diamant"}) then {Ressources6 = (player getVariable "Diamant")};
if (!isnil {player getVariable "HeroineTransformer"}) then {Ressources7 = (player getVariable "HéroineTransformer")};
if (!isnil {player getVariable "DiamantTransformer"}) then {Ressources8 = (player getVariable "DiamantTransformer")};
if (!isnil {player getVariable "PetroleTransformer"}) then {Ressources9 = (player getVariable "PetroleTransformer")};
if (!isnil {player getVariable "SableTransformer"}) then {Ressources14 = (player getVariable "SableTransformer")};
if (!isnil {player getVariable "BoisTransformer"}) then {Ressources15 = (player getVariable "BoisTransformer")};
if (!isnil {player getVariable "PierreTransformer"}) then {Ressources16 = (player getVariable "PierreTransformer")};

lbAdd [77774,format["Héroine : %1",(Ressources)]];
lbAdd [77774,format["Pomme : %1",(Ressources1)]];
lbAdd [77774,format["Sable : %1",(Ressources11)]];
lbAdd [77774,format["Bois : %1",(Ressources12)]];
lbAdd [77774,format["Pierre : %1",(Ressources13)]];
lbAdd [77774,format["Poisson : %1",(Ressources2)]];
lbAdd [77774,format["Petrole : %1",(Ressources3)]];
lbAdd [77774,format["Fer : %1",(Ressources4)]];
lbAdd [77774,format["Fer Transformer: %1",(Ressources10)]];
lbAdd [77774,format["Charbon : %1",(Ressources5)]];
lbAdd [77774,format["Diamant : %1",(Ressources6)]];
lbAdd [77774,format["Héroine Transformer : %1",(Ressources7)]];
lbAdd [77774,format["Diamant Transformer : %1",(Ressources8)]];
lbAdd [77774,format["Petrole Transformer : %1",(Ressources9)]];
lbAdd [77774,format["Sable Transformer : %1",(Ressources14)]];
lbAdd [77774,format["Bois Transformer : %1",(Ressources15)]];
lbAdd [77774,format["Pierre Transformer : %1",(Ressources16)]];
	};
